## User
POST http://localhost:3000/api/users/addNewUser
Content-Type: application/json

{
    "username": "hieu89",
    "password": "hieupass"
}

###
GET http://localhost:3000/api/users/getAllUser

###
PATCH http://localhost:3000/api/users/updateUser
Content-Type: application/json  

{
    "_id": "61f2507f8db81258c1dd86dd",
    "username": "hieu12",
    "password": "hieupass"
}

###
DELETE http://localhost:3000/api/users/deleteUser
Content-Type: application/json

{
    "_id": "61f2997900913f345c3d5861"
}


##POST
### 
POST http://localhost:3000/api/posts/addNewPost
Content-Type: application/json

{
    "title": "test tag 2",
    "content": "test tag 2",
    "author": "61f2507f8db81258c1dd86dd",
    "tags": ["h1", "h2"]
}

###
GET http://localhost:3000/api/posts/getAllPost


### Pagination
GET http://localhost:3000/api/posts/getAllPost?page=1&limit=5


### Get post detail
GET http://localhost:3000/api/posts/getAllPost/61f27536f1099e4bbc4fc215


###
PATCH http://localhost:3000/api/posts/updatePost
Content-Type: application/json  

{
    "_id": "61f250e18db81258c1dd86e3",
    "title": "test update",
    "content": "update content",
    "author": "61f2507f8db81258c1dd86dd"
}

###
DELETE http://localhost:3000/api/posts/deletePost/61f250e18db81258c1dd86e3

###Tag
GET http://localhost:3000/api/tags/getAllTags

###
POST http://localhost:3000/api/tags/addNewTag
Content-Type: application/json

{
    "name": "travel 99"
}